// eslint.config.js — SillyQuiz JavaScript lint config
module.exports = [
  {
    files: ["interno/frontend/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        EventSource: "readonly",
        URL: "readonly",
        Worker: "readonly",
        Blob: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        Proxy: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "writable",
        self: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "warn",
      "no-redeclare": "error",
      "no-duplicate-case": "error",
      "no-constant-condition": "warn",
      "no-empty": ["warn", { allowEmpty: true }],
      "no-extra-semi": "warn",
      "no-unreachable": "error",
      eqeqeq: ["warn", "smart"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",
    },
  },
];
