/**
 * scratch-codegen.js — Export AOT machine to multiple target languages
 *
 * Convierte la máquina JSON compilada por ScratchAOT a código ejecutable en:
 *   - Python 3 (asyncio)
 *   - TypeScript/Node.js
 *   - C# (.NET 8)
 *   - Rust (tokio)
 *
 * API:
 *   CodeGen.export(machine, target, opts) -> string
 *   CodeGen.exportToFile(machine, target, filePath, opts) -> Promise<void>
 */

(function (global) {
  'use strict';

  const ScratchBlocks = global.ScratchBlocks
    || (typeof require !== 'undefined' ? require('./scratch-blocks.js').ScratchBlocks : null);

  const REGISTRY = ScratchBlocks ? ScratchBlocks.registry : null;

  function indent(n) { return '  '.repeat(n); }
  function esc(s) { return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n'); }

  const CodeGen = {
    SUPPORTED: ['python', 'typescript', 'csharp', 'rust', 'go', 'gdscript'],

    /** Resolve nested reporter/boolean args to their callable form. */
    _resolveArgsForTarget(node, target) {
      const def = REGISTRY ? REGISTRY[node.opcode] : null;
      if (!def) return node.args;
      
      const resolved = {};
      for (const [token, spec] of Object.entries(def.args)) {
        const val = node.args[token];
        if (!val) { resolved[token] = val; continue; }
        
        if (spec.type === 'reporter' && val?.opcode) {
          // Nested reporter: return the args for the nested call
          resolved[token] = { __nested: 'reporter', opcode: val.opcode, args: val.args };
        } else if (spec.type === 'boolean' && val?.opcode) {
          // Nested boolean: return the args for the nested call
          resolved[token] = { __nested: 'boolean', opcode: val.opcode, args: val.args };
        } else {
          resolved[token] = val;
        }
      }
      return resolved;
    },

    /** Exporta la máquina a código en el lenguaje objetivo. */
    export(machine, target, opts = {}) {
      if (!this.SUPPORTED.includes(target)) {
        throw new Error('Target no soportado: ' + target + '. Use: ' + this.SUPPORTED.join(', '));
      }
      const fnMap = { python: '_toPython', typescript: '_toTypeScript', csharp: '_toCSharp', rust: '_toRust', go: '_toGo', gdscript: '_toGDScript' };
      return this[fnMap[target]](machine, opts);
    },

    // ---- PYTHON 3 (asyncio) ----
    _toPython(machine, opts) {
      const lines = [];
      lines.push('# Generated by SillyQuiz Builder v' + (machine.version || 1));
      lines.push('# Mode: ' + (opts.modeName || 'exported_mode'));
      lines.push('# Compiled at: ' + (machine.compiledAt || new Date().toISOString()));
      lines.push('');
      lines.push('import asyncio');
      lines.push('import json');
      lines.push('from dataclasses import dataclass');
      lines.push('from typing import Any, Dict, List, Optional');
      lines.push('');

      // Runtime state class
      lines.push('@dataclass');
      lines.push('class GameState:');
      lines.push(indent(1) + 'data: Dict[str, Any] = None');
      lines.push('');
      lines.push('    def __post_init__(self):');
      lines.push(indent(2) + 'if self.data is None: self.data = {}');
      lines.push('');
      lines.push('    def get(self, key: str, default=None):');
      lines.push(indent(2) + 'return self.data.get(key, default)');
      lines.push('');
      lines.push('    def set(self, key: str, value: Any):');
      lines.push(indent(2) + 'self.data[key] = value');
      lines.push('');

      // Provider stubs
      lines.push('class Providers:');
      lines.push(indent(1) + '@staticmethod');
      lines.push(indent(2) + 'def reporter(opcode: str, args: Dict, ctx) -> Any:');
      lines.push(indent(3) + 'return Providers._reporter_impl(opcode, args, ctx)');
      lines.push(indent(1) + '@staticmethod');
      lines.push(indent(2) + 'def boolean(opcode: str, args: Dict, ctx) -> bool:');
      lines.push(indent(3) + 'return Providers._boolean_impl(opcode, args, ctx)');
      lines.push(indent(1) + '@staticmethod');
      lines.push(indent(2) + 'async def side_effect(opcode: str, args: Dict, ctx) -> Dict:');
      lines.push(indent(3) + 'return await Providers._side_effect_impl(opcode, args, ctx)');
      lines.push('');

      // Generated reporters
      lines.push(indent(1) + '@staticmethod');
      lines.push(indent(2) + 'def _reporter_impl(opcode, args, ctx):');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'reporter' && !def.disabledInProd) {
          lines.push(indent(3) + `if opcode == '${opcode}': return Providers._rep_${opcode}(args, ctx)`);
        }
      }
      lines.push(indent(3) + 'return None');
      lines.push('');

      // Generated booleans
      lines.push(indent(1) + '@staticmethod');
      lines.push(indent(2) + 'def _boolean_impl(opcode, args, ctx):');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'boolean' && !def.disabledInProd) {
          lines.push(indent(3) + `if opcode == '${opcode}': return Providers._bool_${opcode}(args, ctx)`);
        }
      }
      lines.push(indent(3) + 'return False');
      lines.push('');

      // Generated side effects
      lines.push(indent(1) + '@staticmethod');
      lines.push(indent(2) + 'async def _side_effect_impl(opcode, args, ctx):');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'stack' && !def.disabledInProd) {
          lines.push(indent(3) + "if opcode == '" + opcode + "': return await Providers._se_" + opcode + "(args, ctx)");
        }
      }
      lines.push(indent(3) + 'return {"ok": True}');
      lines.push('');

      // Event handlers
      for (const [eventOpcode, chains] of Object.entries(machine.events || {})) {
        lines.push(`async def on_${eventOpcode}(state: GameState):`);
        if (!chains || chains.length === 0) {
          lines.push(indent(1) + 'pass');
        } else {
          chains.forEach((chain, i) => {
            lines.push(indent(1) + `await _chain_${eventOpcode}_${i}(state)`);
          });
        }
        lines.push('');
        
        chains.forEach((chain, i) => {
          lines.push(`async def _chain_${eventOpcode}_${i}(state: GameState):`);
          CodeGen._emitPythonChain(chain, 1, lines, eventOpcode, i);
          lines.push('');
        });
      }

      // Main runner
      lines.push('async def run(event: str, initial_state: Dict = None):');
      lines.push(indent(1) + 'state = GameState(initial_state or {})');
      lines.push(indent(1) + `handler = globals().get('on_' + event)`);
      lines.push(indent(1) + 'if handler: await handler(state)');
      lines.push(indent(1) + 'return state.data');
      lines.push('');

      lines.push('if __name__ == "__main__":');
      lines.push(indent(1) + 'import sys');
      lines.push(indent(1) + 'event = sys.argv[1] if len(sys.argv) > 1 else "on_mode_init"');
      lines.push(indent(1) + 'result = asyncio.run(run(event))');
      lines.push(indent(1) + 'print(json.dumps(result, indent=2))');

      return lines.join('\n');
    },

    _emitPythonChain(chain, depth, lines, eventOpcode, chainIdx) {
      if (!chain) return;
      const node = chain;
      const def = REGISTRY ? REGISTRY[node.opcode] : null;
      
      if (def?.type === 'hat') {
        // Skip hat in chain execution
        if (node.next) CodeGen._emitPythonChain(node.next, depth, lines, eventOpcode, chainIdx);
        return;
      }

      if (def?.hasBody) {
        // Container blocks
        const emitBody = (body, d) => {
          if (!body) return;
          // body is an array of blocks (a chain), iterate over each block
          body.forEach(block => CodeGen._emitPythonChain(block, d, lines, eventOpcode, chainIdx));
        };
        
        switch (node.opcode) {
          case 'if_then': {
            const resolved = this._resolveArgsForTarget(node, 'python');
            const cond = (resolved.COND && resolved.COND.__nested === 'boolean')
              ? `Providers.boolean('${resolved.COND.opcode}', ${JSON.stringify(resolved.COND.args)}, state)`
              : JSON.stringify(resolved.COND);
            lines.push(indent(depth) + `if Providers.boolean('compare', ${cond}, state):`);
            emitBody(node.body, depth + 1);
            break;
          }
          case 'if_then_else': {
            const resolved = this._resolveArgsForTarget(node, 'python');
            const cond = (resolved.COND && resolved.COND.__nested === 'boolean')
              ? `Providers.boolean('${resolved.COND.opcode}', ${JSON.stringify(resolved.COND.args)}, state)`
              : JSON.stringify(resolved.COND);
            lines.push(indent(depth) + `if Providers.boolean('compare', ${cond}, state):`);
            emitBody(node.body, depth + 1);
            lines.push(indent(depth) + 'else:');
            emitBody(node.elseBody, depth + 1);
            break;
          }
          case 'repeat_until': {
            const resolved = this._resolveArgsForTarget(node, 'python');
            const cond = (resolved.COND && resolved.COND.__nested === 'boolean')
              ? `Providers.boolean('${resolved.COND.opcode}', ${JSON.stringify(resolved.COND.args)}, state)`
              : JSON.stringify(resolved.COND);
            lines.push(indent(depth) + 'while True:');
            lines.push(indent(depth + 1) + `if Providers.boolean('compare', ${cond}, state): break`);
            emitBody(node.body, depth + 1);
            break;
          }
          case 'try_catch_fallback':
            lines.push(indent(depth) + 'try:');
            if (node.body) CodeGen._emitPythonChain(node.body, depth + 1, lines, eventOpcode, chainIdx);
            lines.push(indent(depth) + 'except Exception:');
            if (node.fallback) CodeGen._emitPythonChain(node.fallback, depth + 1, lines, eventOpcode, chainIdx);
            break;
          case 'for_each_in_list':
            lines.push(indent(depth) + `for ${node.args.VAR || 'item'} in state.get('list_${node.args.NAME}', []):`);
            if (node.body) CodeGen._emitPythonChain(node.body, depth + 1, lines, eventOpcode, chainIdx);
            break;
          case 'repeat_for_range':
            const from = node.args.FROM || 0;
            const to = node.args.TO || 10;
            const step = node.args.STEP || 1;
            lines.push(indent(depth) + `for ${node.args.VAR || 'i'} in range(${from}, ${to} + 1, ${step}):`);
            if (node.body) CodeGen._emitPythonChain(node.body, depth + 1, lines, eventOpcode, chainIdx);
            break;
        }
      } else {
        // Stack blocks
        if (def?.type === 'stack') {
          lines.push(indent(depth) + `await Providers.side_effect('${node.opcode}', ${JSON.stringify(node.args)}, state)`);
        } else if (def?.type === 'reporter' || def?.type === 'boolean') {
          // Nested reporters handled in args resolution
        }
      }

      if (node.next) CodeGen._emitPythonChain(node.next, depth, lines, eventOpcode, chainIdx);
    },

    // ---- TYPESCRIPT / NODE.JS ----
    _toTypeScript(machine, opts) {
      const lines = [];
      lines.push('// Generated by SillyQuiz Builder v' + (machine.version || 1));
      lines.push('// Mode: ' + (opts.modeName || 'exported_mode'));
      lines.push('');
      lines.push('interface GameState {');
      lines.push('  [key: string]: any;');
      lines.push('}');
      lines.push('');
      lines.push('interface BlockResult { ok: boolean; delay?: number; result?: any; error?: string }');
      lines.push('');

      // Providers class
      lines.push('class Providers {');
      lines.push('  static reporter(opcode: string, args: any, ctx: any): any {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'reporter' && !def.disabledInProd) {
          lines.push(`    if (opcode === '${opcode}') return this._rep_${opcode}(args, ctx);`);
        }
      }
      lines.push('    return null;');
      lines.push('  }');
      lines.push('');
      lines.push('  static boolean(opcode: string, args: any, ctx: any): boolean {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'boolean' && !def.disabledInProd) {
          lines.push(`    if (opcode === '${opcode}') return this._bool_${opcode}(args, ctx);`);
        }
      }
      lines.push('    return false;');
      lines.push('  }');
      lines.push('');
      lines.push('  static async sideEffect(opcode: string, args: any, ctx: any): Promise<BlockResult> {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'stack' && !def.disabledInProd) {
          lines.push(`    if (opcode === '${opcode}') return this._se_${opcode}(args, ctx);`);
        }
      }
      lines.push('    return { ok: true };');
      lines.push('  }');
      lines.push('}');
      lines.push('');

      // Event handlers
      for (const [eventOpcode, chains] of Object.entries(machine.events || {})) {
        lines.push(`async function on${eventOpcode.replace(/_/g, '')}(state: GameState): Promise<void> {`);
        chains.forEach((chain, i) => {
          lines.push(`  await chain${eventOpcode.replace(/_/g, '')}${i}(state);`);
        });
        lines.push('}');
        lines.push('');

        chains.forEach((chain, i) => {
          lines.push(`async function chain${eventOpcode.replace(/_/g, '')}${i}(state: GameState): Promise<void> {`);
          CodeGen._emitTSChain(chain, 1, lines);
          lines.push('}');
          lines.push('');
        });
      }

      // Main export
      lines.push('export async function run(event: string, initialState: GameState = {}): Promise<GameState> {');
      lines.push('  const handler = (globalThis as any)[\'on\' + event.replace(/_/g, \'\')];');
      lines.push('  if (handler) await handler(initialState);');
      lines.push('  return initialState;');
      lines.push('}');
      lines.push('');

      lines.push('export default { run, Providers };');

      return lines.join('\n');
    },

    _emitTSChain(chain, depth, lines) {
      if (!chain) return;
      const node = chain;
      const def = REGISTRY ? REGISTRY[node.opcode] : null;
      const ind = '  '.repeat(depth);

      if (def?.type === 'hat') {
        if (node.next) CodeGen._emitTSChain(node.next, depth, lines);
        return;
      }

      if (def?.hasBody) {
        switch (node.opcode) {
          case 'if_then':
            lines.push(`${ind}if (Providers.boolean('compare', ${JSON.stringify(node.args)}, state)) {`);
            if (node.body) CodeGen._emitTSChain(node.body, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
          case 'if_then_else':
            lines.push(`${ind}if (Providers.boolean('compare', ${JSON.stringify(node.args)}, state)) {`);
            if (node.body) CodeGen._emitTSChain(node.body, depth + 1, lines);
            lines.push(`${ind}} else {`);
            if (node.elseBody) CodeGen._emitTSChain(node.elseBody, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
          case 'repeat_times':
            lines.push(`${ind}for (let i = 0; i < ${node.args.N || 1}; i++) {`);
            if (node.body) CodeGen._emitTSChain(node.body, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
        }
      } else if (def?.type === 'stack') {
        lines.push(`${ind}await Providers.sideEffect('${node.opcode}', ${JSON.stringify(node.args)}, state);`);
      }
      if (node.next) CodeGen._emitTSChain(node.next, depth, lines);
    },

    // ---- C# (.NET 8) ----
    _toCSharp(machine, opts) {
      const ns = opts.namespace || 'SillyQuiz.Mode';
      const lines = [];
      lines.push('// Generated by SillyQuiz Builder v' + (machine.version || 1));
      lines.push('// Mode: ' + (opts.modeName || 'ExportedMode'));
      lines.push('');
      lines.push('using System;');
      lines.push('using System.Collections.Generic;');
      lines.push('using System.Threading.Tasks;');
      lines.push('using System.Text.Json;');
      lines.push('');
      lines.push(`namespace ${ns};`);
      lines.push('');
      lines.push('public class GameState {');
      lines.push('  public Dictionary<string, object> Data { get; } = new();');
      lines.push('  public T Get<T>(string key, T defaultValue = default) => Data.TryGetValue(key, out var v) ? (T)v : defaultValue;');
      lines.push('  public void Set(string key, object value) => Data[key] = value;');
      lines.push('}');
      lines.push('');
      lines.push('public record BlockResult(bool Ok, int? Delay = null, object Result = null, string Error = null);');
      lines.push('');
      lines.push('public static class Providers {');
      lines.push('  public static object Reporter(string opcode, Dictionary<string, object> args, GameState ctx) {');
      lines.push('    return opcode switch {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'reporter' && !def.disabledInProd) {
          lines.push(`    "${opcode}" => Rep_${opcode}(args, ctx),`);
        }
      }
      lines.push('    _ => null');
      lines.push('  };');
      lines.push('  }');
      lines.push('');
      lines.push('  public static bool Boolean(string opcode, Dictionary<string, object> args, GameState ctx) {');
      lines.push('    return opcode switch {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'boolean' && !def.disabledInProd) {
          lines.push(`    "${opcode}" => Bool_${opcode}(args, ctx),`);
        }
      }
      lines.push('    _ => false');
      lines.push('  };');
      lines.push('  }');
      lines.push('');
      lines.push('  public static async Task<BlockResult> SideEffect(string opcode, Dictionary<string, object> args, GameState ctx) {');
      lines.push('    return opcode switch {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'stack' && !def.disabledInProd) {
          lines.push(`    "${opcode}" => await Se_${opcode}(args, ctx),`);
        }
      }
      lines.push('    _ => new BlockResult(true)');
      lines.push('  };');
      lines.push('  }');
      lines.push('}');
      lines.push('');

      // Event handlers
      for (const [eventOpcode, chains] of Object.entries(machine.events || {})) {
        const methodName = eventOpcode.replace(/_/g, '');
        lines.push(`public static async Task On${methodName}(GameState state) {`);
        chains.forEach((_, i) => {
          lines.push(`  await Chain${methodName}${i}(state);`);
        });
        lines.push('}');
        lines.push('');

        chains.forEach((chain, i) => {
          lines.push(`private static async Task Chain${methodName}${i}(GameState state) {`);
          CodeGen._emitCSChain(chain, 1, lines);
          lines.push('}');
          lines.push('');
        });
      }

      // Main entry
      lines.push('public static async Task<GameState> Run(string evt, GameState initial = null) {');
      lines.push('  var state = initial ?? new GameState();');
      lines.push('  var method = typeof(Program).GetMethod($"On{evt.Replace("_", "")}");');
      lines.push('  if (method != null) await (Task)method.Invoke(null, new object[] { state });');
      lines.push('  return state;');
      lines.push('}');

      return lines.join('\n');
    },

    _emitCSChain(chain, depth, lines) {
      if (!chain) return;
      const node = chain;
      const def = REGISTRY ? REGISTRY[node.opcode] : null;
      const ind = ' '.repeat(depth * 4);

      if (def?.type === 'hat') {
        if (node.next) CodeGen._emitCSChain(node.next, depth, lines);
        return;
      }

      if (def?.hasBody) {
        switch (node.opcode) {
          case 'if_then':
            lines.push(`${ind}if ((bool)Providers.Boolean("compare", ${JSON.stringify(node.args).replace(/"/g, '\\"')}, state)) {`);
            if (node.body) CodeGen._emitCSChain(node.body, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
          case 'if_then_else':
            lines.push(`${ind}if ((bool)Providers.Boolean("compare", ${JSON.stringify(node.args).replace(/"/g, '\\"')}, state)) {`);
            if (node.body) CodeGen._emitCSChain(node.body, depth + 1, lines);
            lines.push(`${ind}} else {`);
            if (node.elseBody) CodeGen._emitCSChain(node.elseBody, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
        }
      } else if (def?.type === 'stack') {
        lines.push(`${ind}await Providers.SideEffect("${node.opcode}", ${JSON.stringify(node.args).replace(/"/g, '\\"')}, state);`);
      }
      if (node.next) CodeGen._emitCSChain(node.next, depth, lines);
    },

    // ---- RUST (tokio) ----
    _toRust(machine, opts) {
      const crate = opts.crateName || 'sillyquiz_mode';
      const lines = [];
      lines.push('//! Generated by SillyQuiz Builder v' + (machine.version || 1));
      lines.push('//! Mode: ' + (opts.modeName || 'exported_mode'));
      lines.push('');
      lines.push('use std::collections::HashMap;');
      lines.push('use serde::{Deserialize, Serialize};');
      lines.push('use tokio;');
      lines.push('');
      lines.push('#[derive(Debug, Default, Serialize, Deserialize)]');
      lines.push('pub struct GameState {');
      lines.push('  pub data: HashMap<String, serde_json::Value>,');
      lines.push('}');
      lines.push('');
      lines.push('impl GameState {');
      lines.push('  pub fn get<T: for \'de Deserialize>(&self, key: &str) -> Option<T> {');
      lines.push('    self.data.get(key).and_then(|v| serde_json::from_value(v.clone()).ok())');
      lines.push('  }');
      lines.push('  pub fn set(&mut self, key: &str, value: impl Serialize) {');
      lines.push('    self.data.insert(key.to_string(), serde_json::to_value(value).ok()?);');
      lines.push('  }');
      lines.push('}');
      lines.push('');
      lines.push('#[derive(Debug, Serialize, Deserialize)]');
      lines.push('pub struct BlockResult {');
      lines.push('  pub ok: bool,');
      lines.push('  pub delay: Option<u64>,');
      lines.push('  pub result: Option<serde_json::Value>,');
      lines.push('  pub error: Option<String>,');
      lines.push('}');
      lines.push('');
      lines.push('pub struct Providers;');
      lines.push('');
      lines.push('impl Providers {');
      lines.push('  pub fn reporter(opcode: &str, args: &serde_json::Value, ctx: &GameState) -> Option<serde_json::Value> {');
      lines.push('    match opcode {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'reporter' && !def.disabledInProd) {
          lines.push(`    "${opcode}" => Self::rep_${opcode}(args, ctx),`);
        }
      }
      lines.push('    _ => None,');
      lines.push('    }');
      lines.push('  }');
      lines.push('');
      lines.push('  pub fn boolean(opcode: &str, args: &serde_json::Value, ctx: &GameState) -> bool {');
      lines.push('    match opcode {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'boolean' && !def.disabledInProd) {
          lines.push(`    "${opcode}" => Self::bool_${opcode}(args, ctx),`);
        }
      }
      lines.push('    _ => false,');
      lines.push('    }');
      lines.push('  }');
      lines.push('');
      lines.push('  pub async fn side_effect(opcode: &str, args: &serde_json::Value, ctx: &mut GameState) -> BlockResult {');
      lines.push('    match opcode {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'stack' && !def.disabledInProd) {
          lines.push(`    "${opcode}" => Self::se_${opcode}(args, ctx).await,`);
        }
      }
      lines.push('    _ => BlockResult { ok: true, ..Default::default() },');
      lines.push('    }');
      lines.push('  }');
      lines.push('}');
      lines.push('');

      // Event handlers
      for (const [eventOpcode, chains] of Object.entries(machine.events || {})) {
        const fnName = eventOpcode.replace(/_/g, '');
        lines.push(`pub async fn on_${fnName}(state: &mut GameState) {`);
        chains.forEach((_, i) => {
          lines.push(`  chain_${fnName}_${i}(state).await;`);
        });
        lines.push('}');
        lines.push('');

        chains.forEach((chain, i) => {
          const fnName2 = eventOpcode.replace(/_/g, '');
          lines.push(`async fn chain_${fnName2}_${i}(state: &mut GameState) {`);
          CodeGen._emitRustChain(chain, 1, lines);
          lines.push('}');
          lines.push('');
        });
      }

      // Main
      lines.push('pub async fn run(event: &str, mut state: GameState) -> GameState {');
      lines.push('  match event {');
      for (const [eventOpcode] of Object.entries(machine.events || {})) {
        const fnName = eventOpcode.replace(/_/g, '');
        lines.push(`    "on_${fnName}" => on_${fnName}(&mut state).await,`);
      }
      lines.push('    _ => {}');
      lines.push('  }');
      lines.push('  state');
      lines.push('}');

      return lines.join('\n');
    },

    _emitRustChain(chain, depth, lines) {
      if (!chain) return;
      const node = chain;
      const def = REGISTRY ? REGISTRY[node.opcode] : null;
      const ind = '  '.repeat(depth);

      if (def?.type === 'hat') {
        if (node.next) CodeGen._emitRustChain(node.next, depth, lines);
        return;
      }

      if (def?.hasBody) {
        switch (node.opcode) {
          case 'if_then':
            lines.push(`${ind}if Providers::boolean("compare", &${JSON.stringify(node.args)}, state) {`);
            if (node.body) CodeGen._emitRustChain(node.body, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
          case 'if_then_else':
            lines.push(`${ind}if Providers::boolean("compare", &${JSON.stringify(node.args)}, state) {`);
            if (node.body) CodeGen._emitRustChain(node.body, depth + 1, lines);
            lines.push(`${ind}} else {`);
            if (node.elseBody) CodeGen._emitRustChain(node.elseBody, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
        }
      } else if (def?.type === 'stack') {
        lines.push(`${ind}Providers::side_effect("${node.opcode}", &${JSON.stringify(node.args)}, state).await;`);
      }
      if (node.next) CodeGen._emitRustChain(node.next, depth, lines);
    },

    // ---- GO (Golang) ----
    _toGo(machine, opts) {
      const pkg = opts.packageName || 'main';
      const lines = [];
      lines.push('// Generated by SillyQuiz Builder v' + (machine.version || 1));
      lines.push('// Mode: ' + (opts.modeName || 'exported_mode'));
      lines.push('');
      lines.push('package ' + pkg);
      lines.push('');
      lines.push('import (');
      lines.push('  "context"');
      lines.push('  "encoding/json"');
      lines.push('  "fmt"');
      lines.push(')');
      lines.push('');
      lines.push('type GameState struct {');
      lines.push('  Data map[string]interface{}');
      lines.push('}');
      lines.push('');
      lines.push('func NewGameState() *GameState {');
      lines.push('  return &GameState{Data: make(map[string]interface{})}');
      lines.push('}');
      lines.push('');
      lines.push('func (s *GameState) Get(key string) interface{} { return s.Data[key] }');
      lines.push('func (s *GameState) Set(key string, value interface{}) { s.Data[key] = value }');
      lines.push('');
      lines.push('type BlockResult struct { Ok bool; Delay int; Result interface{}; Error string }');
      lines.push('');
      lines.push('type Providers struct{}');
      lines.push('');
      lines.push('func (p Providers) Reporter(opcode string, args map[string]interface{}, ctx *GameState) interface{} {');
      lines.push('  switch opcode {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'reporter' && !def.disabledInProd) {
          lines.push(`    case "${opcode}": return p.rep_${opcode}(args, ctx)`);
        }
      }
      lines.push('    default: return nil');
      lines.push('  }');
      lines.push('}');
      lines.push('');
      lines.push('func (p Providers) Boolean(opcode string, args map[string]interface{}, ctx *GameState) bool {');
      lines.push('  switch opcode {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'boolean' && !def.disabledInProd) {
          lines.push(`    case "${opcode}": return p.bool_${opcode}(args, ctx)`);
        }
      }
      lines.push('    default: return false');
      lines.push('  }');
      lines.push('}');
      lines.push('');
      lines.push('func (p Providers) SideEffect(opcode string, args map[string]interface{}, ctx *GameState) BlockResult {');
      lines.push('  switch opcode {');
      for (const [opcode, def] of Object.entries(REGISTRY || {})) {
        if (def.type === 'stack' && !def.disabledInProd) {
          lines.push(`    case "${opcode}": return p.se_${opcode}(args, ctx)`);
        }
      }
      lines.push('    default: return BlockResult{Ok: true}');
      lines.push('  }');
      lines.push('}');
      lines.push('');

      // Event handlers
      for (const [eventOpcode, chains] of Object.entries(machine.events || {})) {
        const fnName = eventOpcode.replace(/_/g, '');
        lines.push(`func On${fnName}(ctx *GameState) {`);
        chains.forEach((_, i) => {
          lines.push(`  chain${fnName}${i}(ctx)`);
        });
        lines.push('}');
        lines.push('');

        chains.forEach((chain, i) => {
          lines.push(`func chain${fnName}${i}(ctx *GameState) {`);
          CodeGen._emitGoChain(chain, 1, lines);
          lines.push('}');
          lines.push('');
        });
      }

      // Main
      lines.push('func Run(event string, initial *GameState) *GameState {');
      lines.push('  if initial == nil { initial = NewGameState() }');
      lines.push('  switch event {');
      for (const [eventOpcode] of Object.entries(machine.events || {})) {
        const fnName = eventOpcode.replace(/_/g, '');
        lines.push(`    case "on_${fnName}": On${fnName}(initial);`);
      }
      lines.push('  }');
      lines.push('  return initial');
      lines.push('}');

      return lines.join('\n');
    },

    _emitGoChain(chain, depth, lines) {
      if (!chain) return;
      const node = chain;
      const def = REGISTRY ? REGISTRY[node.opcode] : null;
      const ind = '\t'.repeat(depth);

      if (def?.type === 'hat') {
        if (node.next) CodeGen._emitGoChain(node.next, depth, lines);
        return;
      }

      if (def?.hasBody) {
        switch (node.opcode) {
          case 'if_then':
            lines.push(`${ind}if Providers{}.Boolean("compare", ${JSON.stringify(node.args)}, ctx) {`);
            if (node.body) CodeGen._emitGoChain(node.body, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
          case 'if_then_else':
            lines.push(`${ind}if Providers{}.Boolean("compare", ${JSON.stringify(node.args)}, ctx) {`);
            if (node.body) CodeGen._emitGoChain(node.body, depth + 1, lines);
            lines.push(`${ind}} else {`);
            if (node.elseBody) CodeGen._emitGoChain(node.elseBody, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
          case 'repeat_times':
            lines.push(`${ind}for i := 0; i < ${node.args.N || 1}; i++ {`);
            if (node.body) CodeGen._emitGoChain(node.body, depth + 1, lines);
            lines.push(`${ind}}`);
            break;
        }
      } else if (def?.type === 'stack') {
        lines.push(`${ind}Providers{}.SideEffect("${node.opcode}", ${JSON.stringify(node.args)}, ctx)`);
      }
      if (node.next) CodeGen._emitGoChain(node.next, depth, lines);
    },

    // ---- GDScript (Godot 4) ----
    _toGDScript(machine, opts) {
      const className = opts.className || 'ExportedMode';
      const lines = [];
      lines.push('# Generated by SillyQuiz Builder v' + (machine.version || 1));
      lines.push('# Mode: ' + (opts.modeName || 'exported_mode'));
      lines.push('');
      lines.push('extends Node');
      lines.push('class_name ' + className);
      lines.push('');
      lines.push('var state: Dictionary = {}');
      lines.push('');
      lines.push('func _ready():');
      lines.push('\tstate = {}');
      lines.push('');
      lines.push('func run(event: String) -> Dictionary:');
      lines.push('\tmatch event:');
      for (const [eventOpcode] of Object.entries(machine.events || {})) {
        const fnName = eventOpcode.replace(/_/g, '');
        lines.push('\t\t"on_' + fnName + '": on_' + fnName + '()');
      }
      lines.push('\t\t_: pass');
      lines.push('\treturn state');
      lines.push('');

      // Event handlers
      for (const [eventOpcode, chains] of Object.entries(machine.events || {})) {
        const fnName = eventOpcode.replace(/_/g, '');
        lines.push('func on_' + fnName + '():');
        chains.forEach((_, i) => {
          lines.push('\tchain_' + fnName + '_' + i + '()');
        });
        lines.push('');

        chains.forEach((chain, i) => {
          lines.push('func chain_' + fnName + '_' + i + '():');
          CodeGen._emitGDChain(chain, 1, lines);
          lines.push('');
        });
      }

      return lines.join('\n');
    },

    _emitGDChain(chain, depth, lines) {
      if (!chain) return;
      const node = chain;
      const def = REGISTRY ? REGISTRY[node.opcode] : null;
      const ind = '\t'.repeat(depth);

      if (def?.type === 'hat') {
        if (node.next) CodeGen._emitGDChain(node.next, depth, lines);
        return;
      }

      if (def?.hasBody) {
        switch (node.opcode) {
          case 'if_then':
            lines.push(ind + 'if Providers.boolean("compare", ' + JSON.stringify(node.args) + ', state):');
            if (node.body) CodeGen._emitGDChain(node.body, depth + 1, lines);
            break;
          case 'if_then_else':
            lines.push(ind + 'if Providers.boolean("compare", ' + JSON.stringify(node.args) + ', state):');
            if (node.body) CodeGen._emitGDChain(node.body, depth + 1, lines);
            lines.push(ind + 'else:');
            if (node.elseBody) CodeGen._emitGDChain(node.elseBody, depth + 1, lines);
            break;
          case 'repeat_times':
            lines.push(ind + 'for i in range(' + (node.args.N || 1) + '):');
            if (node.body) CodeGen._emitGDChain(node.body, depth + 1, lines);
            break;
        }
      } else if (def?.type === 'stack') {
        lines.push(ind + 'await Providers.side_effect("' + node.opcode + '", ' + JSON.stringify(node.args) + ', state)');
      }
      if (node.next) CodeGen._emitGDChain(node.next, depth, lines);
    },

    /** Exporta a archivo. */
    async exportToFile(machine, target, filePath, opts = {}) {
      const code = this.export(machine, target, opts);
      if (typeof require !== 'undefined') {
        const fs = require('fs').promises;
        await fs.writeFile(filePath, code, 'utf8');
      } else {
        // Browser: trigger download
        const blob = new Blob([code], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filePath.split('/').pop() || `mode.${target}`;
        a.click();
        URL.revokeObjectURL(url);
      }
    }
  };

  global.CodeGen = CodeGen;
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CodeGen };
  }
})(typeof window !== 'undefined' ? window : this);